---
name: Netlify Next.js Deploy
author: Jo Colina - fork by Veloi
description: Netlify Deploy, forked to build Next.js
inputs:
  NETLIFY_AUTH_TOKEN:
    description: Auth token to use with netlify
    required: true
    default: ""
  NETLIFY_SITE_ID:
    description: Your Netlify site id
    required: true
    default: ""
  NETLIFY_DEPLOY_TO_PROD:
    description: Should the site be deployed to production?
    required: false
    default: "false"
  NETLIFY_DEPLOY_MESSAGE:
    description: A deploy message
    required: false
    default: ""
  deploy_alias:
    description: Deployment Subdomain name
    required: false
    default: ""
  WORKING_DIRECTORY:
    description: Set current working directory
    default: ""
outputs:
  NETLIFY_OUTPUT:
    description: netlify command output
    value: ""
  NETLIFY_PREVIEW_URL:
    description: deployment preview URL
    value: ""
  NETLIFY_LOGS_URL:
    description: deployment preview logs url
    value: ""
  NETLIFY_LIVE_URL:
    description: deployment URL
    value: ""
runs:
  using: composite
  steps:
      - run: ${{ github.action_path }}/entrypoint.sh
        shell: bash
        env:
          NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ inputs.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: ${{ inputs.NETLIFY_DEPLOY_TO_PROD }}
          NETLIFY_DEPLOY_MESSAGE: ${{ inputs.NETLIFY_DEPLOY_MESSAGE }}
          DEPLOY_ALIAS: ${{ inputs.deploy_alias }}
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
      
branding:
  icon: activity
  color: blue
